### ISSUE TITLE
Question on how to train my own model

### ISSUE THREAD

**Issue by yurunsheng1** [yuanming-hu/exposure#1]
Hi,
When I am training my model, I meet a problem:

FileNotFoundError: [Errno 2] No such file or directory: '/data/yuanming/fivek_dataset/sup_batched80aug_daylight/image_raw.npy'

I am confused about what image_raw.npy, image.npy and image_retouched.npy means and how to build my 
own image_raw.npy, image.npy and image_retouched.npy ?

Also, can anyone give me some guides on how to train my own model? Thanks so much!

**Comment by yuanming-hu** [comment]
Sure. Will do it tonight.

**Comment by yuanming-hu** [comment]
Hi,

I updated the instructions for training.
Please close this issue if it works on your side.

Thanks,
Yuanming

**Comment by yurunsheng1** [comment]
It works. Thanks so much for your help!
