### ISSUE TITLE
Critic gradient norm and penalty

### ISSUE THREAD

**Issue by SugarMasuo** [yuanming-hu/exposure#11]
Hi, I'm reading the code of GAN net, I cannot understand the meaning of "Critic gradient norm and penalty"part, do you have any reference? Thanks a lot!

**Comment by yuanming-hu** [comment]
This should answer your question https://arxiv.org/abs/1704.00028 :-)

**Comment by SugarMasuo** [comment]
@yuanming-hu ,Thanks!
