### ISSUE TITLE
Some questions about mask

### ISSUE THREAD

**Issue by zhongtao93** [yuanming-hu/exposure#17]
Hi, thank you for you sharing code! I found that exposureNet can generate a mask when generate a filter parameters, however, only 5-6 parameters and get_mask() function can produce a H*W*1 mask. There is no hint in paper about how to train the mask and how to generate the mask, so can you help me to explain theory about the mask using in exposureNet.

Thank you very much!

**Comment by yuanming-hu** [comment]
Hi,

Thanks for the question. Actually, the `mask` is an experimental feature and in the all results reported in the paper, masking is disabled.

Basically, you only need a few parameters for an alpha mask, whose alpha value is a linear combination of x, y, lumiance etc. Then we pass it to a `sigmoid` function to make its range within `[0, 1]`.
