### ISSUE TITLE
FiveK dataset

### ISSUE THREAD

**Issue by varunsaboo** [yuanming-hu/exposure#19]
Hi,
Thank you for releasing the code for this paper.
In addition to Artist C in the FiveK dataset, do you also have zip files available for the other 4 artists?

Thanks!

**Comment by yuanming-hu** [comment]
Hi, following previous work we do not use images from the other four
artists. However, following
https://github.com/yuanming-hu/exposure/wiki/Preparing-data-for-the-MIT-Adobe-FiveK-Dataset-with-Lightroom
it should be straightforward to generate them yourself.
