### ISSUE TITLE
Visualizing results for the 1000 RAW test images?

### ISSUE THREAD

**Issue by thelittlekid** [yuanming-hu/exposure#20]
Hi, @yuanming-hu. Thanks for sharing the codes. 
I'm wondering if there is an easy way to visualize the results for those 1000 RAW test images (part 3 of the MIT-Adobe FiveK Dataset). 
Thanks.

**Comment by yuanming-hu** [comment]
Thanks for the question. I will deal with it tonight.

**Comment by yuanming-hu** [comment]
Hi,

The results are here: https://github.com/yuanming-hu/exposure_models/releases/download/v0.0.1/test_outputs.zip

To generate them yourself, please download the package of test input images: https://github.com/yuanming-hu/exposure_models/releases/download/v0.0.1/test_set.zip
and run
```
python3 evaluate.py example pretrained data/fivek_dataset/test_set/*.tif
```

and wait for a while (~60 minutes, seemingly bounded by some non-GPU computation which I haven't got a time to figure out yet).

**Comment by thelittlekid** [comment]
Thanks!
