### ISSUE TITLE
Could you pls provide a pretrained model ?

### ISSUE THREAD

**Issue by syan1992** [yuanming-hu/exposure#3]
As title. Really interest in your work. Many thanks.

**Comment by yuanming-hu** [comment]
I think there is already one: https://github.com/yuanming-hu/exposure#using-the-pretrained-model

**Comment by yuanming-hu** [comment]
Just make sure you have cloned the repo recursively:
```
git clone https://github.com/yuanming-hu/exposure --recursive
```
