### ISSUE TITLE
How to generate the training data from the very begining

### ISSUE THREAD

**Issue by vissac** [yuanming-hu/exposure#31]
Hi yuanming, I'm try to generate the training data from fivek origin data and I'm come into some problems, you said 
In the Collections list, select collection Inputs/Input with Daylight WhiteBalance minus 1.5.
but I'm confused at minus 1.5, what does minus 1.5 mean? Minus tone? tint? or exposure?

**Comment by vissac** [comment]
> Thanks for the question. I think that's exposure, as they appear darker. I'm just following some previous works to select this collection.

Got it~ Thank you. And I also download the data after your process, but I cannot reproduce the data in image_raw.npy to its origin dng.  How can I connect the data in npy with origin dng. And in meta_raw.pkl I only find the name of the files, is it necessary for recover the origin data from npy?

**Comment by yuanming-hu** [comment]
Sorry for the delayed reply. The `image_raw.py` file is the pre-processed dataset for fast data loading during training. It is not necessary to recover dngs from that file.
