### ISSUE TITLE
Segmentation fault while runing evaluation code

### ISSUE THREAD

**Issue by wakananai** [yuanming-hu/exposure#32]
Hi, Yuanming,

While I run the command at **Using the pretrained model** section , I get segmentation fault error message.

There is my platform and package information:

- ubuntu 18.04
- GPU: K80
- nvidia driver version 390.77
- python 3.6
- tensorflow-gpu 1.11.0
- opencv-pytohn 3.4.3.18
- tiffile 0.15.1
- scikit-image 0.14.1

The following is error message from dmesg:

> "segfault at 0 ip 00007fce957b5216 sp 00007fccd9ff1480 error 4 in _pywrap_tensorflow_internal.so[7fce90acb000+2aa45000]"

And I found that seg fault might be occurred at **Line 804(self.sess.run) in net.py**.
Do you have any idea how to solve it?
Thanks for your help.

**Comment by thelittlekid** [comment]
You might want to downgrade tensorflow to 1.10.x. I got the same error with tensorflow 1.11

**Comment by wakananai** [comment]
Thanks @thelittlekid . I downgrade tensorflow to 1.10.0 and everything works fine. 
If anyone knows the correlation between tensorflow1.11 and segmentation fault on the codes, please leave a comment. 
Thanks a lot.

**Comment by yuanming-hu** [comment]
Thank you guys, for resolving this issue. It seems to me a TensorFlow bug.. Let's see if it will be fixed in future versions of tensorflow.
