### ISSUE TITLE
Quantitative evaluation using histogram_intersection.py

### ISSUE THREAD

**Issue by thelittlekid** [yuanming-hu/exposure#34]
Hi @yuanming-hu , 
Thanks for sharing your codes. Could you please explain a little bit on how to obtain the quantitative evaluation results using histogram_intersection?
I tried to feed two directories as the input arguments and modified line 51 to the following: 
`patch = cv2.resize(new_image, dsize=(80, 80), interpolation=cv2.INTER_AREA)`, 
but got an error at line 30 inside get_histograms(images). The error message was: TypeError: iteration over a 0-d array. 
Thanks!

**Comment by yuanming-hu** [comment]
Thanks for the question. I will take a look sometime tonight.

**Comment by yuanming-hu** [comment]
Hi, I think it is fixed now in the latest update. It was caused by python and opencv upgrade.

**Comment by thelittlekid** [comment]
It works now. Thanks!
