### ISSUE TITLE
Pretrained model Miss

### ISSUE THREAD

**Issue by SugarMasuo** [yuanming-hu/exposure#4]
Hello @yuanming-hu 
Thanks for your code! I'm studying relative exposure topic for stitching task.
The pretrained model in the models folder is missing. Do you have any trained models now?
I would really appreciate it if you can share one trained tensorflow model.
Thank you!

**Comment by yuanming-hu** [comment]
Hi , pls check FAQ 3. Thanks.

**Comment by SugarMasuo** [comment]
Hi, I used git clone https://github.com/yuanming-hu/exposure --recursive, but  the models folder is always empty. If I click the models folder in the web, it alerts 404 error. I don't know why. Thanks

**Comment by yuanming-hu** [comment]
Oh sorry. It was broken for some reason and I believe it's fixed now.
Thanks for letting me know! :-)

**Comment by yuanming-hu** [comment]
Please close this issue if you find it works on your side @SugarMasuo

**Comment by SugarMasuo** [comment]
Thanks!
