### ISSUE TITLE
Undo gamma correction

### ISSUE THREAD

**Issue by SugarMasuo** [yuanming-hu/exposure#7]
Hi @yuanming-hu ,why do you do 'linearize_ProPhotoRGB' or 'Linearize sRGB'  first for the input images?
I tried to change the paramater from 1.001 to 2.2, the results differ a lot. I wonder what's the reason of reference for this 'linearize'. Thanks a lot!

**Comment by zhongtao93** [comment]
The same question, @SugarMasuo you can see that all training input also do 'Linearize sRGB'

**Comment by yuanming-hu** [comment]
Hi guys,

I'm not sure if I understand you correctly. Please read FAQ 4 where I think I answer part of your questions, and let me know if you have more!
